name: build-macos

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PYTHON_CONFIGURE_OPTS: --enable-shared
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install brew system libraries
        run: |
          brew install libtiff libjpeg webp little-cms2 libxml2 zlib

      - name: Set environment variables for compiler flags
        run: |
          echo "LDFLAGS=-L$(brew --prefix zlib)/lib $LDFLAGS" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix zlib)/include $CPPFLAGS" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix zlib)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Setup Python 2 with pyenv
        uses: gabrielfalcao/pyenv-action@v16
        with:
          default: 2.7.18

      - name: Install Python requirements
        run: |
          python --version
          pip --version
          pip install -r requirements.txt
          echo "PYTHON=$(pyenv which python)" >> $GITHUB_ENV

      - name: Create disk image
        run: |
          hdiutil create -volname exe -size 500m -layout GPTSPUD -fs 'Journaled HFS+' -type UDIF installs/osx/exe

      - name: Build package
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: |
          pip install py2app httplib2
          # Monkey patch to avoid exception on modulegraph library using python3 regex
          sed -i '' 's/re.compile(rb"/re.compile(r"/g' /Users/runner/hostedtoolcache/pyenv_root/2.3.23/x64/versions/2.7.18/lib/python2.7/site-packages/modulegraph/util.py
          npm install -g appdmg
          cd installs/osx
          python make.py -p

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-macos
          path: installs/osx/INTEF-exe-*.dmg
